title: Wedding — Yoshida-Teetor
baseurl: ""   # the subpath of your site, e.g. /blog
url: "https://wedding.yoshidateetor.com"

# Build settings
markdown: kramdown

collections_dir: _collections
collections:
  home:
    order:
      - welcome.md
      - when.md
      - where.md

sass:
  sass_dir: _sass

include:
  - node_modules/jquery/dist/jquery.slim.min.js
  - node_modules/popper.js/dist/umd/popper.min.js
  - node_modules/bootstrap/dist/bootstrap.min.js

# Header settings
header:
  pages:
    - index.md
    - location/index.md
    - travel.md
    - lodging.md
    - contact.md
